### ISSUE TITLE
Group id change bug

### ISSUE THREAD

**Issue by oventi** [impactoss/impactoss-server#325]
This url works fine, http://localhost:3000/actions?cat=177&connected=indicators:279&expand=2&group=6&order=desc&sort=updated_at&subgroup=5

but this fails, http://localhost:3000/actions?cat=177&connected=indicators:279&expand=2&group=1&order=desc&sort=updated_at&subgroup=5

the only change is the parameter group

**Comment by oventi** [comment]
@tmfrnz I found this issue while working on the bookmark feature. Can see if it is reproducible on the master branch?

**Comment by tmfrnz** [comment]
This is probably due to the fact that taxonomy "1" does not tag actions, and can thus neither group them. You will see that  `tags_measures` is set to false in the seed file:
https://github.com/impactoss/impactoss-server/blob/master/db/seeds.rb#L34

The only "legal" groups with the demo configuration are taxonomies 5 "Thematic cluster" and 6 "Organisation" (where `tags_measures: true`.

So the question goes back to you to check how the wrong taxonomy id was stored in the group field?

**Comment by oventi** [comment]
No need to work on this issue.
